package game;

public enum GameStateEnum {
    //Server
    WAITING_PLAYERS_CHOOSE_SIDE,
    WAITING_PLAYERS_CHOOSE_PLAY,

    //Client
    PLAYER_CONNECTING_SERVER,
    PLAYER_CHOOSING_SIDE,
    PLAYER_WAITING_OTHERS,
    PLAYER_WAITING_OPPONENT_CHOOSE,
    PLAYER_CHOOSING_PLAY,
    PLAYER_WAITING_RESULT,
    PLAYER_RESTART_OR_END,
    PLAYER_WAITING_OPPONENT_RESTART,

    //Both
    ENDED,
}
