package game;

public enum GameState {
    //Server
    WAITING_PLAYERS,
    WAITING_PLAYERS_CHOOSE_SIDE,


    //Client
    PLAYER_CONNECTING_SERVER,
    PLAYER_CHOOSING_SIDE,
    PLAYER_WAITING_OTHERS,
    PLAYER_WAITING_OPPONENT_CHOOSE,
    PLAYER_CHOOSING_PLAY,

    //Both
    ENDED,
}
