package game;

public enum GameState {
    //Server
    WAITING_PLAYERS,
    WAITING_PLAYERS_CHOOSE_SIDE,
    WAITING_PLAYERS_CHOOSE_PLAY,
    COMPUTE_RESULT,
    WAITING_PLAYERS_RESTART_OR_END,

    //Client
    PLAYER_CONNECTING_SERVER,
    PLAYER_CHOOSING_SIDE,
    PLAYER_WAITING_OTHERS,
    PLAYER_WAITING_OPPONENT_CHOOSE,
    PLAYER_CHOOSING_PLAY,
    PLAYER_WAITING_RESULT,
    PLAYER_RESTART_OR_END,

    //Both
    ENDED,
}
